# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

# Color theme.
#   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`.
color_theme = "ocean"
# Enable users to switch between day and night mode?
day_night = true

# Font style.
#   Choose from `default`, `classic`, or `playfair`.
font = "playfair"

# Description for social sharing and search engines. If undefined, author role is used in place.
description = """
Personal webpage of Alessandro De Luca, researcher and assistant professor at
University of Naples Federico II"""

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a vistor shares your site on Twitter.
twitter = ""

# Diplay a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
logo = ""

# Enable global source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight = false
# highlight_languages = ["r"]  # Add support for highlighting additional languages
# highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = true

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = true

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "15:04"

############################
## Contact Widget setup   ##
############################

# Enter contact details (optional). To hide a field, clear it to "".
email = "DELETETHISalessandro.deluca@unina.it"
phone = "+39 08176 85948"
address = """
DIETI, Università di Napoli Federico II

via Claudio, 21 – 80125 Napoli, Italy"""

# Office hours: use `<br>` to insert a line break, or set to "" to remove office hours
office_hours = ""

# Enter an optional link for booking appointments (e.g. calendly.com).
appointment_url = ""

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
contact_links = [
  # {icon = "twitter", icon_pack = "fab", name = "DM Me", link = "https://twitter.com/Twitter"},
  {icon = "skype", icon_pack = "fab", name = "Skype Me", link = "skype:fudo?call"},
  # {icon = "keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
  # {icon = "comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://discourse.gohugo.io"},
  # {icon = "telegram", icon_pack = "fab", name = "Telegram Me", link = "https://telegram.me/@Telegram"},
  ]

# Display a map.
# To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
# a map provider below.
# To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
#   https://developers.google.com/maps/documentation/javascript/get-api-key
# To use OpenStreetMap tiles, set `map = 2`.
# To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
#   https://www.mapbox.com/studio/account/tokens
# To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
#
# Map provider:
#   0: No map
#   1: Google Maps
#   2: OpenStreetMap (Mapnik)
#   3: OpenStreetMap (Mapbox)
map = 0
map_api_key = ""
latitude = "37.4275"
longitude = "-122.1697"
zoom = 15

############################
## Plugins                ##
############################

# Load CSS and JS plugins
#   E.g. To load `/assets/css/custom.css`, set `plugins_css = ["custom"]`.
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_css = []
plugins_js  = []

############################
## Advanced options       ##
############################

# Get your avatar from Gravatar.com? (true/false)
gravatar = false

# Align the main menu to the right of the page? (true/false)
menu_align_right = true

# Show estimated reading time for posts?
reading_time = false

# Display comment count? Requires commenting to be enabled.
comment_count = false

# Display next/previous section pager?
section_pager = false

# Enable native social sharing buttons?
sharing = true

# OLD?
# Publication types.
#   Used to categorize publications.
#   The index of the publication type in the list is used as its unique numerical identifier.
#   The numeric ID is used in a publication's frontmatter to categorize it.
#   The language can be edited below.
#   For multilingual sites, `publication_types` can be copied to each language section at the end of this file and
#   translated.
publication_types = [
  'Uncategorized',  # 0
  'Conference paper',  # 1
  'Journal article',  # 2
  'Manuscript',  # 3
  'Thesis',  # 4
  'Book',  # 5
  'Book section'  # 6
]

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "January, 2006"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2

# Search.
[search]
  # Search provider:
  #   0: No search engine
  #   1: Built-in (Fuse)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false


# OLD?
# Configuration of talk pages.
[talks]
  # Show talk time?
  time = true

# OLD Highlight.js options
#   highlight
#     Enable global source code highlighting?  If false, you can
#     override it for a particular page in that page's preamble.
#
#     Example: highlight = true
#
#   highlight_languages
#     Add support for highlighting additional languages. Support for
#     languages mentioned here will be included in all pages.
#
#     Example: highlight_languages = ["go", "lisp", "ocaml"]
#
#   highlight_style
#     Choose a different CSS style for highlighting source
#     code. Setting this option in a page's preamble has no
#     effect.
#
#     Example: highlight_style = "github-gist"
#
#   For the list of supported languages and styles, see:
#   https://cdnjs.com/libraries/highlight.js/
#
#   For more info on the highlighting options, see:
#   https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
